cron: 0 8 * * *
image: image-registry.openshift-image-registry.svc:5000/d8a8f9-tools/endorsement-reminder:test
env: test
applicationURL: https://test.healthprovideridentityportal.gov.bc.ca
aspnetcoreEnvironment: Staging
